export const words = [
  // 143 words
  ['anbieten', 'bietet an', 'bot an', 'hat angeboten', 'предлагать'],
  ['anfangen', 'fängt an', 'fing an', 'hat angefangen', 'начинать'],
  ['backen', 'backt', 'backte', 'hat gebacken', 'печь'],
  ['befehlen', 'befiehlt', 'befahl', 'hat befohlen', 'приказывать'],
  ['beginnen', 'beginnt', 'begann', 'hat begonnen', 'начинать'],
  ['beißen', 'beißt', 'biss', 'hat gebissen', 'кусать'],
  ['beschließen', 'beschließt', 'beschloss', 'hat beschlossen', 'решать'],
  ['betrügen', 'betrügt', 'betrog', 'hat betrogen', 'обманывать'],
  ['beweisen', 'beweist', 'bewies', 'hat bewiesen', 'доказывать'],
  ['bewerben', 'bewirbt', 'bewarb', 'hat beworben', 'подавать заявление'],
  ['biegen', 'biegt', 'bog', 'hat/ist gebogen', 'гнуть'],
  ['bieten', 'bietet', 'bot', 'hat geboten', 'предлагать'],
  ['binden', 'bindet', 'band', 'hat gebunden', 'связывать'],
  ['bitten', 'bittet', 'bat', 'hat gebeten', 'просить'],
  ['blasen', 'bläst', 'blies', 'hat geblasen', 'дуть'],
  ['bleiben', 'bleibt', 'blieb', 'ist geblieben', 'оставаться'],
  ['braten', 'brät', 'briet', 'hat gebraten', 'жарить'],
  ['brechen', 'bricht', 'brach', 'hat/ist gebrochen', 'ломать'],
  ['brennen', 'brennt', 'brannte', 'hat gebrannt', 'гореть'],
  ['bringen', 'bringt', 'brachte', 'hat gebracht', 'приносить'],
  ['denken', 'denkt', 'dachte', 'hat gedacht', 'думать'],
  ['dürfen', 'darf', 'durfte', 'hat gedurft', 'мочь'],
  ['empfangen', 'empfängt', 'empfing', 'hat empfangen', 'получать'],
  ['empfehlen', 'empfiehlt', 'empfahl', 'hat empfohlen', 'рекомендовать'],
  ['empfinden', 'empfindet', 'empfand', 'hat empfunden', 'чувствовать'],
  ['entscheiden', 'entscheidet', 'entschied', 'hat entschieden', 'решать'],
  ['erhalten', 'erhält', 'erhielt', 'hat erhalten', 'получать'],
  ['erschrecken', 'erschrickt', 'erschrak', 'ist erschrocken', 'пугаться'],
  ['essen', 'isst', 'aß', 'hat gegessen', 'есть'],
  ['fahren', 'fährt', 'fuhr', 'ist gefahren', 'ехать'],
  ['fallen', 'fällt', 'fiel', 'ist gefallen', 'падать'],
  ['fangen', 'fängt', 'fing', 'hat gefangen', 'ловить'],
  ['finden', 'findet', 'fand', 'hat gefunden', 'находить'],
  ['fliegen', 'fliegt', 'flog', 'ist geflogen', 'летать'],
  ['fliehen', 'flieht', 'floh', 'ist geflohen', 'бежать'],
  ['fließen', 'fließt', 'floss', 'ist geflossen', 'течь'],
  ['fressen', 'frisst', 'fraß', 'hat gefressen', 'жрать'],
  ['frieren', 'friert', 'fror', 'hat/ist gefroren', 'замерзать'],
  ['gebären', 'gebärt', 'gebar', 'hat geboren', 'рожать'],
  ['geben', 'gibt', 'gab', 'hat gegeben', 'давать'],
  ['gefallen', 'gefällt', 'gefiel', 'hat gefallen', 'нравиться'],
  ['gehen', 'geht', 'ging', 'ist gegangen', 'идти'],
  ['gelingen', 'gelingt', 'gelang', 'ist gelungen', 'удаваться'],
  ['gelten', 'gilt', 'galt', 'hat gegolten', 'действовать'],
  ['genießen', 'genießt', 'genoss', 'hat genossen', 'наслаждаться'],
  ['geschehen', 'geschieht', 'geschah', 'ist geschehen', 'происходить'],
  ['gewinnen', 'gewinnt', 'gewann', 'hat gewonnen', 'выигрывать'],
  ['gießen', 'gießt', 'goss', 'hat gegossen', 'лить'],
  ['gleiten', 'gleitet', 'glitt', 'ist geglitten', 'скользить'],
  ['graben', 'gräbt', 'grub', 'hat gegraben', 'копать'],
  ['greifen', 'greift', 'griff', 'hat gegriffen', 'хватать'],
  ['haben', 'hat', 'hatte', 'hat gehabt', 'иметь'],
  ['halten', 'hält', 'hielt', 'hat gehalten', 'держать'],
  ['hängen', 'hängt', 'hing', 'hat gehangen', 'висеть'],
  ['heben', 'hebt', 'hob', 'hat gehoben', 'поднимать'],
  ['heißen', 'heißt', 'hieß', 'hat geheißen', 'звать'],
  ['helfen', 'hilft', 'half', 'hat geholfen', 'помогать'],
  ['kennen', 'kennt', 'kannte', 'hat gekannt', 'знать'],
  ['klingen', 'klingt', 'klang', 'hat geklungen', 'звучать'],
  ['kommen', 'kommt', 'kam', 'ist gekommen', 'приходить'],
  ['können', 'kann', 'konnte', 'hat gekonnt', 'мочь'],
  ['laden', 'lädt', 'lud', 'hat geladen', 'загружать'],
  ['lassen', 'lässt', 'ließ', 'hat gelassen', 'позволять'],
  ['laufen', 'läuft', 'lief', 'ist gelaufen', 'бежать'],
  ['leiden', 'leidet', 'litt', 'hat gelitten', 'страдать'],
  ['leihen', 'leiht', 'lieh', 'hat geliehen', 'одолжить'],
  ['lesen', 'liest', 'las', 'hat gelesen', 'читать'],
  ['liegen', 'liegt', 'lag', 'hat gelegen', 'лежать'],
  ['lügen', 'lügt', 'log', 'hat gelogen', 'врать'],
  ['messen', 'misst', 'maß', 'hat gemessen', 'измерять'],
  ['mögen', 'mag', 'mochte', 'hat gemocht', 'любить'],
  ['müssen', 'muss', 'musste', 'hat gemusst', 'должен'],
  ['nehmen', 'nimmt', 'nahm', 'hat genommen', 'брать'],
  ['nennen', 'nennt', 'nannte', 'hat genannt', 'называть'],
  ['pfeifen', 'pfeift', 'pfiff', 'hat gepfiffen', 'свистеть'],
  ['raten', 'rät', 'riet', 'hat geraten', 'советовать'],
  ['reiben', 'reibt', 'rieb', 'hat gerieben', 'тереть'],
  ['reißen', 'reißt', 'riss', 'hat gerissen', 'рвать'],
  ['reiten', 'reitet', 'ritt', 'ist geritten', 'ездить верхом'],
  ['riechen', 'riecht', 'roch', 'hat gerochen', 'пахнуть'],
  ['rufen', 'ruft', 'rief', 'hat gerufen', 'кричать'],
  ['saufen', 'säuft', 'soff', 'hat gesoffen', 'пить (животное)'],
  ['schaffen', 'schafft', 'schuf', 'hat geschaffen', 'создавать'],
  ['scheiden', 'scheidet', 'schied', 'ist geschieden', 'разводиться'],
  ['scheinen', 'scheint', 'schien', 'hat geschienen', 'светить'],
  ['schieben', 'schiebt', 'schob', 'hat geschoben', 'толкать'],
  ['schießen', 'schießt', 'schoss', 'hat geschossen', 'стрелять'],
  ['schlafen', 'schläft', 'schlief', 'hat geschlafen', 'спать'],
  ['schlagen', 'schlägt', 'schlug', 'hat geschlagen', 'бить'],
  ['schleichen', 'schleicht', 'schlich', 'ist geschlichen', 'красться'],
  ['schließen', 'schließt', 'schloss', 'hat geschlossen', 'закрывать'],
  ['schmeißen', 'schmeißt', 'schmiss', 'hat geschmissen', 'бросать'],
  ['schmelzen', 'schmilzt', 'schmolz', 'ist geschmolzen', 'плавить'],
  ['schneiden', 'schneidet', 'schnitt', 'hat geschnitten', 'резать'],
  ['schreiben', 'schreibt', 'schrieb', 'hat geschrieben', 'писать'],
  ['schreien', 'schreit', 'schrie', 'hat geschrien', 'кричать'],
  ['schweigen', 'schweigt', 'schwieg', 'hat geschwiegen', 'молчать'],
  ['schwimmen', 'schwimmt', 'schwamm', 'ist geschwommen', 'плавать'],
  ['schwören', 'schwört', 'schwor', 'hat geschworen', 'клясться'],
  ['sehen', 'sieht', 'sah', 'hat gesehen', 'видеть'],
  ['sein', 'ist', 'war', 'ist gewesen', 'быть'],
  ['senden', 'sendet', 'sandte', 'hat gesandt', 'посылать'],
  ['singen', 'singt', 'sang', 'hat gesungen', 'петь'],
  ['sinken', 'sinkt', 'sank', 'ist gesunken', 'тонуть'],
  ['sitzen', 'sitzt', 'saß', 'hat gesessen', 'сидеть'],
  ['spinnen', 'spinnt', 'spann', 'hat gesponnen', 'прясть'],
  ['sprechen', 'spricht', 'sprach', 'hat gesprochen', 'говорить'],
  ['springen', 'springt', 'sprang', 'ist gesprungen', 'прыгать'],
  ['stechen', 'sticht', 'stach', 'hat gestochen', 'колоть'],
  ['stehen', 'steht', 'stand', 'hat gestanden', 'стоять'],
  ['stehlen', 'stiehlt', 'stahl', 'hat gestohlen', 'красть'],
  ['steigen', 'steigt', 'stieg', 'ist gestiegen', 'подниматься'],
  ['sterben', 'stirbt', 'starb', 'ist gestorben', 'умирать'],
  ['stoßen', 'stößt', 'stieß', 'hat gestoßen', 'толкать'],
  ['streichen', 'streicht', 'strich', 'hat gestrichen', 'красить'],
  ['streiten', 'streitet', 'stritt', 'hat gestritten', 'спорить'],
  ['tragen', 'trägt', 'trug', 'hat getragen', 'носить'],
  ['treffen', 'trifft', 'traf', 'hat getroffen', 'встречать'],
  ['treiben', 'treibt', 'trieb', 'hat getrieben', 'гнать'],
  ['treten', 'tritt', 'trat', 'hat getreten', 'наступать'],
  ['trinken', 'trinkt', 'trank', 'hat getrunken', 'пить'],
  ['tun', 'tut', 'tat', 'hat getan', 'делать'],
  ['vergessen', 'vergisst', 'vergaß', 'hat vergessen', 'забывать'],
  ['verlieren', 'verliert', 'verlor', 'hat verloren', 'терять'],
  ['verzeihen', 'verzeiht', 'verzieh', 'hat verziehen', 'прощать'],
  ['wachsen', 'wächst', 'wuchs', 'ist gewachsen', 'расти'],
  ['waschen', 'wäscht', 'wusch', 'hat gewaschen', 'мыть'],
  ['weichen', 'weicht', 'wich', 'ist gewichen', 'отступать'],
  ['weisen', 'weist', 'wies', 'hat gewiesen', 'указывать'],
  ['wenden', 'wendet', 'wandte', 'hat gewandt', 'поворачивать'],
  ['werben', 'wirbt', 'warb', 'hat geworben', 'рекламировать'],
  ['werden', 'wird', 'wurde', 'ist geworden', 'становиться'],
  ['werfen', 'wirft', 'warf', 'hat geworfen', 'бросать'],
  ['wiegen', 'wiegt', 'wog', 'hat gewogen', 'взвешивать'],
  ['wissen', 'weiß', 'wusste', 'hat gewusst', 'знать'],
  ['ziehen', 'zieht', 'zog', 'hat gezogen', 'тянуть'],
  ['zwingen', 'zwingt', 'zwang', 'hat gezwungen', 'принуждать'],
];

export const verbsMitPrep = [
  // 46 verbs
  [
    ['sich entscheiden', 'für'],
    ['Die Familie entscheidet sich', 'für', 'die Wohnung mit Balkon.'],
    ['Решаться на ..., Принимать решение в пользу ...'],
  ],
  [['erkennen', 'an'], ['Ich habe ihn', 'an', 'der Stimme erkannt.'], ['Узнавать по ...']],
  [
    ['sich freuen', 'über'],
    ['Vielen Dank! Ich freue mich', 'über', 'die Blumen.'],
    ['Радоваться чему либо в прошлом или настоящем'],
  ],
  [['sich freuen', 'auf'], ['Die Kinder freuen sich', 'auf', 'Weihnachten'], ['Радоваться чему либо в будущем']],
  [['gehen', 'um'], ['Es geht heute', 'um', 'das Präteritum.'], ['Речь идет о ...']],
  [['sich gewöhnen', 'an'], ['Haben Sie sich schon', 'an', 'das deutsche Brot gewöhnt?'], ['Привыкать к ...']],
  [['glauben', 'an'], ['Wir glauben', 'an', 'eine erfolgreiche Zukunft.'], ['Верить в ...']],
  [['sich halten', 'an'], ['Der Mann hält sich', 'an', 'die Regeln.'], ['Придерживаться, соблюдать']],
  [['sich handeln', 'um'], ['Es handelt sich', 'um', 'eine exotische Frucht.'], ['Речь идет о ..., Дело касается ...']],
  [['hoffen', 'auf'], ['Sie hofft', 'auf', 'gutes Wetter.'], ['Надеяться на ...']],
  [['sich interessieren', 'für'], ['Wafaa interessiert sich', 'für', 'Basketball.'], ['Интересоваться чем либо']],
  [
    ['sich konzentrieren', 'auf'],
    ['Ich konzentriere mich', 'auf', 'meine Arbeit.'],
    ['Сконцентриорваться на чем либо'],
  ],
  [['sich kümmern', 'um'], ['Sie kümmert sich', 'um', 'ihre alten Eltern.'], ['Заботиться о ..., Беспокоиться о ...']],
  [['lachen', 'über'], ['Wir lachen', 'über', 'den guten Witz.'], ['Смеяться над ...']],
  [['nachdenken', 'über'], ['Worüber denkst du oft', 'nach?'], ['Размышлять о ..., Думать о ...,']],
  [['schreiben', 'über'], ['Wir schreiben', 'über', 'unseren letzten Urlaub.'], ['Писать о ...']],
  [['sorgen', 'für'], ['Die Eltern sorgen', 'für', 'ihre Kinder.'], ['Заботиться о ..., Обеспечивать']],
  [['sprechen', 'über'], ['Er spricht', 'über', 'das Fußballspiel.'], ['Говорить о ..., Обсуждать']],
  [
    ['staunen', 'über'],
    ['Der Lehrer staunt', 'über', 'den Fleiß der Schüler.'],
    ['Удивляться чему либо, Быть пораженным чем либо'],
  ],
  [['teilnehmen', 'an'], ['Wir nehmen alle', 'an', 'der Prüfung teil.'], ['Участвовать в ...']],
  [['sich treffen', 'mit'], ['Er trifft sich am Samstag', 'mit', 'seinen Freunden.'], ['Встречаться']],
  [
    ['sich unterhalten', 'über'],
    ['Sandro und Karim unterhalten sich', 'über', 'Fußball.'],
    ['Разговаривать о ..., Беседовать о...'],
  ],
  [['sich verlassen', 'auf'], ['Er verlässt sich', 'auf', 'seinen Kollegen.'], ['Положиться на ..., Доверяться']],
  [['verstoßen', 'gegen'], ['Der Dieb verstößt', 'gegen', 'Gesetze.'], ['Нарушить, Пойти против (правил)']],
  [
    ['verzichten', 'auf'],
    ['Sie kann', 'auf', 'Kaffee nicht verzichten.'],
    ['Отказываться от ..., Воздерживаться от...'],
  ],
  [['sich vorbereiten', 'auf'], ['Wir bereiten uns', 'auf', 'den Ausflug vor.'], ['Подготовиться']],
  [['warten', 'auf'], ['Morgens warten viele Leute', 'auf', 'den Bus.'], ['Ждать, Ожидать чего либо']],
  [['sich wundern', 'über'], ['Karim wundert sich', 'über', 'die deutschen Traditionen.'], ['Удивляться чему либо']],
  [['zubereiten', 'aus'], ['Wir bereiten das Essen heute nur', 'aus', 'frischen Produkten zu.'], ['Приготовить из']],
  [['achten', 'auf'], ['Worauf sollte man', 'bei', 'der Berufswahl achten?'], ['Обращать внимание на, Следить за']],
  [['ankommen', 'auf'], ['Es kommt', 'auf', 'die persönlichen Interessen an.'], ['Зависеть от, Иметь значение']],
  [
    ['sich anpassen', 'an'],
    ['In einem fremden Land sollte man sich', 'an', 'die wichtigen Gepflogenheiten anpassen.'],
    ['Приспособиться к, Адаптироваться к'],
  ],
  [
    ['aufkommen', 'für'],
    ['Malaika Hadrawi kann', 'für', 'ihren Lebensunterhalt aufkommen.'],
    ['Брать на себя ответственность за, Оплачивать'],
  ],
  [
    ['sich aufregen', 'über'],
    ['Die Menschen regen sich', 'über', 'die hohen Benzinpreise auf.'],
    ['Волноваться из-за, Раздражаться из-за'],
  ],
  [['sich bedanken', 'für'], ['Ich möchte mich', 'für', 'deine Hilfe bedanken.'], ['Благодарить за']],
  [['sich beklagen', 'über'], ['Die alte Dame beklagt sich', 'über', 'das Essen im Krankenhaus.'], ['Жаловаться на']],
  [
    ['sich bemühen', 'um'],
    ['Toma Popescu hat sich in Rumänien erfolglos', 'um', 'eine Arbeitsstelle bemüht.'],
    ['Стараться добиться, Прилагать усилия'],
  ],
  [
    ['sich beschweren', 'über'],
    ['Die Nachbarn beschweren sich', 'über', 'den Dreck im Treppenhaus.'],
    ['Жаловаться на'],
  ],
  [['sich bewerben', 'um'], ['Die Stelle ist toll! Bewirbst du dich', 'um', 'sie?'], ['Подавать заявку на, Соискать']],
  [
    ['bitten', 'um'],
    ['Malaika Hadrawi bittet eine Kollegin', 'um', 'Hilfe bei der Betreuung ihres Kindes.'],
    ['Просить о'],
  ],
  [['denken', 'an'], ['Denken Sie', 'an', 'den Lebenslauf?'], ['Думать о, Вспоминать о']],
  [['diskutieren', 'über'], ['Worüber diskutiert ihr denn gerade', 'über?', ''], ['Обсуждать, Дискутировать о']],
  [['sich entschuldigen', 'für'], ['Er entschuldigt sich', 'für', 'die Verspätung.'], ['Извиняться за']],
  [
    ['sich erinnern', 'an'],
    ['Anita Jiménez erinnert sich oft', 'an', 'ihre Freunde in Argentinien.'],
    ['Вспоминать о, Помнить о'],
  ],
  [['abhängen', 'von'], ['Der Erfolg hängt', 'von', 'der Vorbereitung ab.'], ['Зависеть от ...']],
  [['träumen', 'von'], ['Sie träumt', 'von', 'einer eigenen Firma.'], ['Мечтать о ...']],
  [['erzählen', 'von'], ['Er erzählt', 'von', 'seiner Reise nach Japan.'], ['Рассказывать о ...']],
  [['überzeugen', 'von'], ['Ich konnte ihn', 'von', 'meiner Idee überzeugen.'], ['Убеждать в ...']],
  [['profitieren', 'von'], ['Alle profitieren', 'von', 'der neuen Regelung.'], ['Извлекать выгоду из ...']],
  [['sich erholen', 'von'], ['Er erholt sich', 'von', 'der Krankheit.'], ['Восстанавливаться после ...']],
  [['sich verabschieden', 'von'], ['Wir verabschieden uns', 'von', 'den Gästen.'], ['Прощаться с ...']],
  [['sich trennen', 'von'], ['Sie hat sich', 'von', 'ihrem Freund getrennt.'], ['Расставаться с ...']],
  [['sich fürchten', 'vor'], ['Das Kind fürchtet sich', 'vor', 'dem Hund.'], ['Бояться чего либо']],
  [['warnen', 'vor'], ['Die Polizei warnt', 'vor', 'Glatteis.'], ['Предупреждать о ...']],
  [['schützen', 'vor'], ['Die Creme schützt die Haut', 'vor', 'der Sonne.'], ['Защищать от ...']],
  [['suchen', 'nach'], ['Wir suchen', 'nach', 'einer Lösung.'], ['Искать что либо']],
  [['fragen', 'nach'], ['Der Gast fragt', 'nach', 'dem Weg.'], ['Спрашивать о ...']],
  [['sich erkundigen', 'nach'], ['Ich erkundige mich', 'nach', 'den Öffnungszeiten.'], ['Наводить справки о ...']],
  [['sich sehnen', 'nach'], ['Er sehnt sich', 'nach', 'Ruhe.'], ['Тосковать по ...']],
  [['gehören', 'zu'], ['Das Projekt gehört', 'zu', 'unseren wichtigsten Aufgaben.'], ['Относиться к ...']],
  [['beitragen', 'zu'], ['Alle sollen', 'zu', 'dem Erfolg beitragen.'], ['Вносить вклад в ...']],
  [['führen', 'zu'], ['Stress kann', 'zu', 'Schlafproblemen führen.'], ['Приводить к ...']],
  [['einladen', 'zu'], ['Sie lädt uns', 'zu', 'ihrer Geburtstagsfeier ein.'], ['Приглашать на ...']],
  [['sich beschäftigen', 'mit'], ['Er beschäftigt sich', 'mit', 'der deutschen Geschichte.'], ['Заниматься чем либо']],
  [['rechnen', 'mit'], ['Wir rechnen', 'mit', 'vielen Besuchern.'], ['Рассчитывать на ..., Ожидать']],
  [
    ['sich auseinandersetzen', 'mit'],
    ['Sie setzt sich kritisch', 'mit', 'dem Thema auseinander.'],
    ['Разбираться с ..., Вникать в ...'],
  ],
  [['anfangen', 'mit'], ['Wir fangen', 'mit', 'dem Unterricht an.'], ['Начинать с ...']],
  [['sich verlieben', 'in'], ['Er hat sich', 'in', 'seine Nachbarin verliebt.'], ['Влюбляться в ...']],
  [['bestehen', 'aus'], ['Das Team besteht', 'aus', 'zehn Personen.'], ['Состоять из ...']],
  [['bestehen', 'auf'], ['Der Kunde besteht', 'auf', 'einer Rückerstattung.'], ['Настаивать на ...']],
  [['zweifeln', 'an'], ['Ich zweifle', 'an', 'seiner Ehrlichkeit.'], ['Сомневаться в ...']],
  [['leiden', 'unter'], ['Viele Menschen leiden', 'unter', 'Stress.'], ['Страдать от ...']],
  [['beruhen', 'auf'], ['Die Studie beruht', 'auf', 'aktuellen Daten.'], ['Основываться на ...']],
  [['hinweisen', 'auf'], ['Der Arzt weist', 'auf', 'die Risiken hin.'], ['Указывать на ...']],
  [['verfügen', 'über'], ['Sie verfügt', 'über', 'gute Sprachkenntnisse.'], ['Располагать чем либо']],
  [['sich beziehen', 'auf'], ['Ich beziehe mich', 'auf', 'Ihre E-Mail.'], ['Ссылаться на ...']],
  [['sich einigen', 'auf'], ['Wir haben uns', 'auf', 'einen Termin geeinigt.'], ['Договариваться о ...']],
];

export const commonPrepositions = [
  //15 preps
  'an',
  'auf',
  'aus',
  'bei',
  'für',
  'gegen',
  'in',
  'mit',
  'nach',
  'über',
  'um',
  'unter',
  'von',
  'vor',
  'zu',
];
